<?php
require '../../librerias/PHPMailer/PHPMailerAutoload.php';
require 'conexion.php';

$consultaId=mysqli_query($conexion, 'SELECT idRegistro, primerNombrel, primerApellido FROM `persona` INNER JOIN correo ON Correo_idCorreo = idCorreo WHERE correo.correo ="'.$_POST["correoRecu"].'"') or die('<p>Error al registrar</p><br>'.mysqli_error($conexion));
 
if($consultaId){
	$consulta=$consultaId->fetch_assoc();

	$mail = new PHPMailer;
	$id=password_hash(rand(0, 1000000), PASSWORD_DEFAULT);
	$to = $_POST["correoRecu"];
	$asunto= "Recuperacion de contraseña PI";
	$name=   $consulta['primerNombrel'].' '.$consulta['primerApellido'] ;
	$email=  "support@progressidea.ml";
	//$sms =   'Parece que solicitaste la recuperación de tu cuenta, para que se haga efectivo el cambio de contraseña pulsa el siguiente link: <br> <a href="https://www.progressidea.tk/registro_login/newPassword.php?idpwd='.$id.'">clickee perrin</a>';
    /////////////////////////////////////////Cuerpo del Correo///////////////////////////
		$sms ='';
		$sms .='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta name="viewport" content="width=device-width, initial-scale=1" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta name="x-apple-disable-message-reformatting" /><meta name="apple-mobile-web-app-capable" content="yes" /><meta name="apple-mobile-web-app-status-bar-style" content="black" /><meta name="format-detection" content="telephone=no" /><title></title><style type="text/css">';;
		$sms .='.ReadMsgBody { width: 100%; background-color: #ebebeb;}';
		$sms .='.ExternalClass {width: 100%; background-color: #ebebeb;}';
		$sms .='.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height:100%;}';
		$sms .='a[x-apple-data-detectors]{';
		$sms .='color:inherit !important;';
		$sms .='text-decoration:none !important;';
		$sms .='font-size:inherit !important;';
		$sms .='font-family:inherit !important;';
		$sms .='font-weight:inherit !important;';
		$sms .='line-height:inherit !important;';
		$sms .='}';
		$sms .='body {-webkit-text-size-adjust:none; -ms-text-size-adjust:none;}';
		$sms .='body {margin:0; padding:0;}';
		$sms .='.yshortcuts a {border-bottom: none !important;}';
		$sms .='.rnb-del-min-width{ min-width: 0 !important; }';
		$sms .='.templateContainer{';
		$sms .='max-width:590px !important;';
		$sms .='width:auto !important;';
		$sms .='}';
		$sms .='img[class="rnb-col-3-img"] {';
		$sms .='max-width:170px;';
		$sms .='}';
		$sms .='img[class="rnb-col-2-img"] {';
		$sms .=' max-width:264px;';
		$sms .='}';
		$sms .='img[class="rnb-col-2-img-side-xs"] {';
		$sms .='max-width:180px;';
		$sms .='}';
		$sms .='img[class="rnb-col-2-img-side-xl"] {';
		$sms .='max-width:350px;';
		$sms .='}';
		$sms .='img[class="rnb-col-1-img"] {';
		$sms .='max-width:550px;';
		$sms .='}';
		$sms .='img[class="rnb-header-img"] {';
		$sms .='max-width:590px;';
		$sms .='}';
		$sms .='.rnb-force-col p, ul, ol{margin:0px!important;}';
		$sms .='.rnb-del-min-width p, ul, ol{margin:0px!important;}';
		$sms .='.rnb-tmpl-width{ width:100%!important;}';
		$sms .='.rnb-social-width{padding-right:15px!important;}';
		$sms .='.rnb-social-align{float:right!important;}';
		$sms .='li{mso-margin-top-alt: 0; mso-margin-bottom-alt: 0;}';
		$sms .='table {mso-table-lspace:0pt; mso-table-rspace:0pt;}';
		$sms .='table, tr, td {border-collapse: collapse;}';
		$sms .='p,a,li,blockquote {mso-line-height-rule:exactly;}';
		$sms .='.msib-right-img { mso-padding-alt: 0 !important;}';
		$sms .='@media only screen and (min-width:590px){';
		$sms .='.templateContainer{width:590px !important;}';
		$sms .='}';
		$sms .='@media screen and (max-width: 360px){';
		$sms .='.rnb-yahoo-width{ width:360px !important;}';
		$sms .='}';
		$sms .='@media screen and (max-width: 380px){';
		$sms .='.element-img-text{ font-size:24px !important;}';
		$sms .='.element-img-text2{ width:230px !important;}';
		$sms .='.content-img-text-tmpl-6{ font-size:24px !important;}';
		$sms .='.content-img-text2-tmpl-6{ width:220px !important;}';
		$sms .='}';
		$sms .='@media screen and (max-width: 480px) {';
		$sms .='td[class="rnb-container-padding"] {';
		$sms .='padding-left: 10px !important;';
		$sms .='padding-right: 10px !important;';
		$sms .='}';
		$sms .='td.rnb-force-nav {';
		$sms .='display: inherit;';
		$sms .='}';
		$sms .='.rnb-social-text-left {';
		$sms .=';width: 100%;';
		$sms .='text-align: center;';
		$sms .='margin-bottom: 15px;';
		$sms .='}';
		$sms .='.rnb-social-text-right {';
		$sms .='width: 100%;';
		$sms .='text-align: center;';
		$sms .='}';
		$sms .='}';
		$sms .='@media only screen and (max-width: 600px) {';
		$sms .='.rnb-text-center {text-align:center !important;}';
		$sms .='th.rnb-force-col {';
		$sms .='display: block;';
		$sms .='padding-right: 0 !important;';
		$sms .='padding-left: 0 !important;';
		$sms .='width:100%;';
		$sms .='}';
		$sms .='table.rnb-container {';
		$sms .='width: 100% !important;';
		$sms .='}';
		$sms .='table.rnb-btn-col-content {';
		$sms .='width: 100% !important;';
		$sms .='}';
		$sms .='table.rnb-col-3 {';
		$sms .='/* unset table align="left/right" */';
		$sms .='float: none !important;';
		$sms .='width: 100% !important;';
		$sms .='/* change left/right padding and margins to top/bottom ones */';
		$sms .='margin-bottom: 10px;';
		$sms .='padding-bottom: 10px;';
		$sms .='}';
		$sms .='table.rnb-last-col-3 {';
		$sms .='/* unset table align="left/right" */';
		$sms .='float: none !important;';
		$sms .='width: 100% !important;';
		$sms .='}';
		$sms .='table.rnb-col-2 {';
		$sms .='/* unset table align="left/right" */';
		$sms .='float: none !important;';
		$sms .='width: 100% !important;';
		$sms .='/* change left/right padding and margins to top/bottom ones */';
		$sms .='margin-bottom: 10px;';
		$sms .='padding-bottom: 10px;';
		$sms .='}';
		$sms .='table.rnb-col-2-noborder-onright {';
		$sms .='/* unset table align="left/right" */';
		$sms .='float: none !important;';
		$sms .='width: 100% !important;';
		$sms .='/* change left/right padding and margins to top/bottom ones */';
		$sms .='margin-bottom: 10px;';
		$sms .='padding-bottom: 10px;';
		$sms .='}';
		$sms .='table.rnb-col-2-noborder-onleft {';
		$sms .='/* unset table align="left/right" */';
		$sms .='float: none !important;';
		$sms .='width: 100% !important;';
		$sms .='/* change left/right padding and margins to top/bottom ones */';
		$sms .='margin-top: 10px;';
		$sms .='padding-top: 10px;';
		$sms .='}';
		$sms .='table.rnb-last-col-2 {';
		$sms .='/* unset table align="left/right" */';
		$sms .='float: none !important;';
		$sms .='width: 100% !important;';
		$sms .='}';
		$sms .='table.rnb-col-1 {';
		$sms .='/* unset table align="left/right" */';
		$sms .='float: none !important;';
		$sms .='width: 100% !important;';
		$sms .='}';
		$sms .='img.rnb-col-3-img {';
		$sms .='width:100% !important;';
		$sms .='}';
		$sms .='img.rnb-col-2-img {';
		$sms .='width:100% !important;';
		$sms .='}';
		$sms .='img.rnb-col-2-img-side-xs {';
		$sms .='width:100% !important;';
		$sms .='}';
		$sms .='img.rnb-col-2-img-side-xl {';
		$sms .='width:100% !important;';
		$sms .='}';
		$sms .='img.rnb-col-1-img {';
		$sms .='width:100% !important;';
		$sms .='}';
		$sms .='img.rnb-header-img {';
		$sms .='width:100% !important;';
		$sms .='margin:0 auto;';
		$sms .='}';
		$sms .='img.rnb-logo-img {';
		$sms .='width:100% !important;';
		$sms .='}';
		$sms .='td.rnb-mbl-float-none {';
		$sms .='float:inherit !important;';
		$sms .='}';
		$sms .='.img-block-center{text-align:center !important;}';
		$sms .='.logo-img-center';
		$sms .='{';
		$sms .='float:inherit !important;';
		$sms .='}';
		$sms .='.rnb-social-align{margin:0 auto !important; float:inherit !important;}';
		$sms .='.rnb-social-center{display:inline-block;}';
		$sms .='.social-text-spacing{margin-bottom:0px !important; padding-bottom:0px !important;}';
		$sms .='.social-text-spacing2{padding-top:15px !important;}';
		$sms .='ul {mso-special-format:bullet;}';
		$sms .='}</style><!--[if gte mso 11]><style type="text/css">table{border-spacing: 0; }table td {border-collapse: separate;}</style><![endif]--><!--[if !mso]><!--><style type="text/css">table{border-spacing: 0;} table td {border-collapse: collapse;}</style> <!--<![endif]--><!--[if gte mso 15]><xml><o:OfficeDocumentSettings><o:AllowPNG/><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]--><!--[if gte mso 9]><xml><o:OfficeDocumentSettings><o:AllowPNG/><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]--></head><body>';
		$sms .='';
		$sms .='<table border="0" align="center" width="100%" cellpadding="0" cellspacing="0" class="main-template" bgcolor="#f9fafc" style="background-color: rgb(249, 250, 252);">';
		$sms .='';	
		$sms .='	<tbody><tr>';
		$sms .='		<td align="center" valign="top">';
		$sms .='		<!--[if gte mso 9]>';
		$sms .='						<table align="center" border="0" cellspacing="0" cellpadding="0" width="590" style="width:590px;">';
		$sms .='						<tr>';
		$sms .='						<td align="center" valign="top" width="590" style="width:590px;">';
		$sms .='						<![endif]-->';
		$sms .='			<table border="0" cellpadding="0" cellspacing="0" width="590" class="templateContainer" style="max-width:590px!important; width: 590px;">';
		$sms .='		<tbody><tr>';
		$sms .='';
		$sms .='		<td align="center" valign="top">';
		$sms .='';
		$sms .='			<table class="rnb-del-min-width" width="100%" cellpadding="0" border="0" cellspacing="0" style="min-width:590px;" name="Layout_0" id="Layout_0">';
		$sms .='				<tbody><tr>';
		$sms .='					<td class="rnb-del-min-width" valign="top" align="center" style="min-width:590px;">';
		$sms .='						<a href="#" name="Layout_0"></a>';
		$sms .='						<table width="100%" cellpadding="0" border="0" height="38" cellspacing="0">';
		$sms .='							<tbody><tr>';
		$sms .='								<td valign="top" height="38">';
		$sms .='									<img width="20" height="38" style="display:block; max-height:38px; max-width:20px;" alt="" src="https://img.mailinblue.com/new_images/rnb/rnb_space.gif">';
		$sms .='								</td>';
		$sms .='							</tr>';
		$sms .='						</tbody></table>';
		$sms .='					</td>';
		$sms .='				</tr>';
		$sms .='			</tbody></table>';
		$sms .='			</td>';
		$sms .='	</tr><tr>';
		$sms .='';
		$sms .='		<td align="center" valign="top">';
		$sms .='';
		$sms .='			<div style="background-color: rgb(255, 255, 255); border-radius: 0px;">';
		$sms .='				';
		$sms .='				<!--[if mso]>';
		$sms .='				<table align="center" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">';
		$sms .='				<tr>';
		$sms .='				<![endif]-->';
		$sms .='				';
		$sms .='				<!--[if mso]>';
		$sms .='				<td valign="top" width="590" style="width:590px;">';
		$sms .='				<![endif]-->';
		$sms .='			';
		$sms .='				<table width="100%" cellpadding="0" border="0" cellspacing="0" name="Layout_2" id="Layout_2"><tbody><tr>';
		$sms .='					<td align="center" valign="top"><a href="#" name="Layout_2"></a>';
		$sms .='						<table border="0" width="100%" cellpadding="0" cellspacing="0" class="rnb-container" bgcolor="#ffffff" style="height: 0px; background-color: rgb(255, 255, 255); border-radius: 0px; border-collapse: separate; padding-left: 20px; padding-right: 20px;"><tbody><tr>';
		$sms .='								<td class="rnb-container-padding" style="font-size: px;font-family: ; color: ;">';
		$sms .='';
		$sms .='									<table border="0" cellpadding="0" cellspacing="0" class="rnb-columns-container" align="center" style="margin:auto;">';
		$sms .='										<tbody><tr>';
		$sms .='';
		$sms .='											<th class="rnb-force-col" align="center" style="text-align: center; font-weight: normal">';
		$sms .='';
		$sms .='												<table border="0" cellspacing="0" cellpadding="0" align="center" class="rnb-col-1">';
		$sms .='';
		$sms .='													<tbody><tr>';
		$sms .='														<td height="10"></td>';
		$sms .='													</tr>';
		$sms .='';
		$sms .='													<tr>';
		$sms .='														<td style="font-family:Arial,Helvetica,sans-serif; color:#3c4858; text-align:center;">';
		$sms .='';
		$sms .='															<span style="color:#3c4858;"><strong><span style="font-size:24px;">ProgressIdea</span></strong></span>';
		$sms .='														</td>';
		$sms .='													</tr>';
		$sms .='													<tr>';
		$sms .='														<td height="10"></td>';
		$sms .='													</tr>';
		$sms .='													</tbody></table>';
		$sms .='												</th></tr>';
		$sms .='									</tbody></table></td>';
		$sms .='							</tr>';
		$sms .='';
		$sms .='						</tbody></table>';
		$sms .='';
		$sms .='					</td>';
		$sms .='				</tr>';
		$sms .='';
		$sms .='			</tbody></table><!--[if mso]>';
		$sms .='				</td>';
		$sms .='				<![endif]-->';
		$sms .='				';
		$sms .='				<!--[if mso]>';
		$sms .='				</tr>';
		$sms .='				</table>';
		$sms .='				<![endif]-->';
		$sms .='			';
		$sms .='		</div></td>';
		$sms .='	</tr><tr>';
		$sms .='';
		$sms .='		<td align="center" valign="top">';
		$sms .='';
		$sms .='			<div style="background-color: rgb(255, 255, 255); border-radius: 0px;">';
		$sms .='				';
		$sms .='				<!--[if mso]>';
		$sms .='				<table align="center" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">';
		$sms .='				<tr>';
		$sms .='				<![endif]-->';
		$sms .='				';
		$sms .='				<!--[if mso]>';
		$sms .='				<td valign="top" width="590" style="width:590px;">';
		$sms .='				<![endif]-->';
		$sms .='				<table class="rnb-del-min-width" width="100%" cellpadding="0" border="0" cellspacing="0" style="min-width:100%;" name="Layout_3" id="Layout_3">';
		$sms .='				<tbody><tr>';
		$sms .='					<td class="rnb-del-min-width" align="center" valign="top">';
		$sms .='						<a href="#" name="Layout_3"></a>';
		$sms .='						<table width="100%" border="0" cellpadding="0" cellspacing="0" class="rnb-container" bgcolor="#ffffff" style="max-width: 100%; min-width: 100%; table-layout: fixed; background-color: rgb(255, 255, 255); border-radius: 0px; border-collapse: separate; padding-left: 20px; padding-right: 20px;">';
		$sms .='							<tbody><tr>';
		$sms .='								<td height="20" style="font-size:1px; line-height:20px; mso-hide: all;">&nbsp;</td>';
		$sms .='							</tr>';
		$sms .='							<tr>';
		$sms .='								<td valign="top" class="rnb-container-padding" align="left">';
		$sms .='';
		$sms .='									<table width="100%" border="0" cellpadding="0" cellspacing="0" class="rnb-columns-container">';
		$sms .='										<tbody><tr>';
		$sms .='											<th class="rnb-force-col" style="text-align: left; font-weight: normal; padding-right: 0px;" width="550" valign="top">';
		$sms .='												<table border="0" valign="top" cellspacing="0" cellpadding="0" align="left" class="rnb-col-1" width="550">';
		$sms .='													<tbody><tr>';
		$sms .='														<td width="100%" class="img-block-center" valign="top" align="left">';
		$sms .='															<table width="100%" cellspacing="0" cellpadding="0" border="0">';
		$sms .='															<tbody>';
		$sms .='																<tr>';
		$sms .='																	<td width="100%" valign="top" align="left" class="img-block-center">';
		$sms .='																		<table style="display:inline-block;" cellspacing="0" cellpadding="0" border="0">';
		$sms .='																			<tbody><tr>';
		$sms .='																				<td>';
		$sms .='																					<div style="border-top:0px None #000;border-right:0px None #000;border-bottom:0px None #000;border-left:0px None #000;display:inline-block;"><div><img border="0" width="550" hspace="0" vspace="0" alt="" class="rnb-col-1-img" src="https://img.mailinblue.com/3341049/images/rnb/original/5fd769e2866a714ecb6c35a7.jpg" style="vertical-align: top; max-width: 800px; float: left;"></div><div style="clear:both;"></div>';
		$sms .='																					</div>';
		$sms .='																			</td>';
		$sms .='																			</tr>';
		$sms .='																		</tbody></table>';
		$sms .='';
		$sms .='																	</td>';
		$sms .='																</tr>';
		$sms .='															</tbody>';
		$sms .='														</table></td>';
		$sms .='													</tr><tr>';
		$sms .='														<td height="10" class="col_td_gap" style="font-size:1px; line-height:10px; mso-hide: all;">&nbsp;</td>';
		$sms .='													</tr><tr>';
		$sms .='														<td style="font-size:24px; font-family:Arial,Helvetica,sans-serif; color:#3c4858; text-align:left;">';
		$sms .='															<span style="color:#3c4858; "><strong><span style="font-size:18px;">Has Olvidado Tu Contraseña?</span></strong></span></td>';
		$sms .='													</tr><tr>';
		$sms .='														<td height="10" class="col_td_gap" style="font-size:1px; line-height:10px; mso-hide: all;">&nbsp;</td>';
		$sms .='													</tr><tr>';
		$sms .='														<td style="font-size:14px; font-family:Arial,Helvetica,sans-serif, sans-serif; color:#3c4858;">';
		$sms .='															<div><div>Hola '.$names.', Este es un correo de recuperacion, si usted no lo ha solicitado comunicarse con soporte tecnico, es probable que su cuenta la hayan intentado robar. .</div>';
		$sms .='</div>';
		$sms .='														</td>';
		$sms .='													</tr>';
		$sms .='													<tr>';
		$sms .='														<td height="10" class="col_td_gap" style="font-size:1px; line-height:10px; mso-hide: all;">&nbsp;</td>';
		$sms .='													</tr><tr>';
		$sms .='														<td valign="top">';
		$sms .='															<table cellpadding="0" border="0" align="left" cellspacing="0" class="rnb-btn-col-content" style="border-collapse: separate;margin:0 auto;">';
		$sms .='																<tbody><tr>';
		$sms .='																	<td width="auto" valign="middle" bgcolor="#34b365" align="left" height="32" style="font-size:14px; font-family:Arial,Helvetica,sans-serif; text-align:center; color:#ffffff; font-weight:normal; padding-left:18px; padding-right:18px; background-color:#34b365; border-radius:4px;border-top:0px None #000;border-right:0px None #000;border-bottom:0px None #000;border-left:0px None #000;">';
		$sms .='																		<span style="color:#ffffff; font-weight:normal;">';
		$sms .='																			<a style="text-decoration:none; color:#ffffff; font-weight:normal;" target="_blank" href="https://www.progressidea.tk/registro_login/newPassword.php?idpwd='.$id.'">Click Aqui Para Recuperar</a>';
		$sms .='																		</span>';
		$sms .='																	</td>';
		$sms .='																</tr>';
		$sms .='															</tbody></table>';
		$sms .='														</td>';
		$sms .='														<!--[if gte mso 9]><span style="font-size:0px;line-height:0px; mso-hide: all;">&nbsp;</span><![endif]-->';
		$sms .='													</tr></tbody></table>';
		$sms .='';
		$sms .='												</th></tr>';
		$sms .='									</tbody></table></td>';
		$sms .='							</tr>';
		$sms .='							<tr>';
		$sms .='								<td height="20" style="font-size:1px; line-height:20px; mso-hide: all;">&nbsp;</td>';
		$sms .='							</tr>';
		$sms .='						</tbody></table>';
		$sms .='';
		$sms .='					</td>';
		$sms .='				</tr>';
		$sms .='			</tbody></table><!--[if mso]>';
		$sms .='				</td>';
		$sms .='				<![endif]-->';
		$sms .='				';
		$sms .='				<!--[if mso]>';
		$sms .='				</tr>';
		$sms .='				</table>';
		$sms .='				<![endif]-->';
		$sms .='				';
		$sms .='			</div></td>';
		$sms .='	</tr><tr>';
		$sms .='';
		$sms .='		<td align="center" valign="top">';
		$sms .='';
		$sms .='			<table class="rnb-del-min-width" width="100%" cellpadding="0" border="0" cellspacing="0" style="min-width:590px;" name="Layout_" id="Layout_">';
		$sms .='				<tbody><tr>';
		$sms .='					<td class="rnb-del-min-width" valign="top" align="center" style="min-width:590px;">';
		$sms .='						<a href="#" name="Layout_"></a>';
		$sms .='						<table width="100%" cellpadding="0" border="0" height="30" cellspacing="0">';
		$sms .='							<tbody><tr>';
		$sms .='								<td valign="top" height="30">';
		$sms .='									<img width="20" height="30" style="display:block; max-height:30px; max-width:20px;" alt="" src="https://img.mailinblue.com/new_images/rnb/rnb_space.gif">';
		$sms .='								</td>';
		$sms .='							</tr>';
		$sms .='						</tbody></table>';
		$sms .='					</td>';
		$sms .='				</tr>';
		$sms .='			</tbody></table>';
		$sms .='			</td>';
		$sms .='	</tr><tr>';
		$sms .='';
		$sms .='		<td align="center" valign="top">';
		$sms .='';
		$sms .='			<div style="background-color: rgb(249, 250, 252);">';
		$sms .='				';
		$sms .='				<table class="rnb-del-min-width rnb-tmpl-width" width="100%" cellpadding="0" border="0" cellspacing="0" style="min-width:590px;" name="Layout_5" id="Layout_5">';
		$sms .='					<tbody><tr>';
		$sms .='						<td class="rnb-del-min-width" align="center" valign="top" bgcolor="#f9fafc" style="min-width: 590px; background-color: rgb(249, 250, 252);">';
		$sms .='							<a href="#" name="Layout_5"></a>';
		$sms .='							<table width="590" class="rnb-container" cellpadding="0" border="0" align="center" cellspacing="0">';
		$sms .='								<tbody><tr>';
		$sms .='									<td height="20" style="font-size:1px; line-height:20px; mso-hide: all;">&nbsp;</td>';
		$sms .='								</tr>';
		$sms .='								<tr>';
		$sms .='									<td valign="top" class="rnb-container-padding" style="font-size: 14px; font-family: Arial,Helvetica,sans-serif; color: #888888;" align="left">';
		$sms .='';
		$sms .='										<table width="100%" border="0" cellpadding="0" cellspacing="0" class="rnb-columns-container">';
		$sms .='											<tbody><tr>';
		$sms .='												<th class="rnb-force-col" style="padding-right:20px; padding-left:20px; mso-padding-alt: 0 0 0 20px; font-weight: normal;" valign="top">';
		$sms .='';
		$sms .='													<table border="0" valign="top" cellspacing="0" cellpadding="0" width="264" align="left" class="rnb-col-2 rnb-social-text-left" style="border-bottom:0;">';
		$sms .='';
		$sms .='														<tbody><tr>';
		$sms .='															<td valign="top">';
		$sms .='																<table cellpadding="0" border="0" align="left" cellspacing="0" class="rnb-btn-col-content">';
		$sms .='																	<tbody><tr>';
		$sms .='																		<td valign="middle" align="left" style="font-size:14px; font-family:Arial,Helvetica,sans-serif; color:#888888; line-height: 16px" class="rnb-text-center">';
		$sms .='																			<div><div>ProgressIdea<br>';
		$sms .='Tegusigalpa, Honduras.<br>';
		$sms .='<a href="#" style="text-decoration: underline; color: rgb(102, 102, 102);">I</a>nfo@ProgressIdea.tk</div>';
		$sms .='</div>';
		$sms .='																		</td></tr>';
		$sms .='																</tbody></table>';
		$sms .='															</td>';
		$sms .='														</tr>';
		$sms .='														</tbody></table>';
		$sms .='													</th><th ng-if="item.text.align=='."'left'".'" class="rnb-force-col rnb-social-width" valign="top" style="mso-padding-alt: 0 20px 0 0; padding-right: 15px;">';
		$sms .='';
		$sms .='													<table border="0" valign="top" cellspacing="0" cellpadding="0" width="246" align="right" class="rnb-last-col-2">';
		$sms .='';
		$sms .='														<tbody><tr>';
		$sms .='															<td valign="top">';
		$sms .='																<table cellpadding="0" border="0" cellspacing="0" class="rnb-social-align" style="float: right;" align="right">';
		$sms .='																	<tbody><tr>';
		$sms .='																		<td valign="middle" class="rnb-text-center" ng-init="width=setSocialIconsBlockWidth(item)" width="246" align="left">';
		$sms .='																			<div class="rnb-social-center">';
		$sms .='																			<table align="left" style="float:left; display: inline-block" border="0" cellpadding="0" cellspacing="0">';
		$sms .='																			<tbody><tr>';
		$sms .='																					<td style="padding:0px 5px 5px 0px; mso-padding-alt: 0px 2px 5px 0px;" align="left">';
		$sms .='																			<span style="color:#ffffff; font-weight:normal;">';
		$sms .='																				<img alt="Facebook" border="0" hspace="0" vspace="0" style="vertical-align:top;" target="_blank" src="https://img.mailinblue.com/new_images/rnb/theme1/rnb_ico_fb.png"></span>';
		$sms .='																			</td></tr></tbody></table>';
		$sms .='																			</div><div class="rnb-social-center">';
		$sms .='																			<table align="left" style="float:left; display: inline-block" border="0" cellpadding="0" cellspacing="0">';
		$sms .='																			<tbody><tr>';
		$sms .='																					<td style="padding:0px 5px 5px 0px; mso-padding-alt: 0px 2px 5px 0px;" align="left">';
		$sms .='																			<span style="color:#ffffff; font-weight:normal;">';
		$sms .='																				<img alt="Twitter" border="0" hspace="0" vspace="0" style="vertical-align:top;" target="_blank" src="https://img.mailinblue.com/new_images/rnb/theme1/rnb_ico_tw.png"></span>';
		$sms .='																			</td></tr></tbody></table>';
		$sms .='																			</div><div class="rnb-social-center">';
		$sms .='																			<table align="left" style="float:left; display: inline-block" border="0" cellpadding="0" cellspacing="0">';
		$sms .='																			<tbody><tr>';
		$sms .='																					<td style="padding:0px 5px 5px 0px; mso-padding-alt: 0px 2px 5px 0px;" align="left">';
		$sms .='																			<span style="color:#ffffff; font-weight:normal;">';
		$sms .='																				<img alt="Google+" border="0" hspace="0" vspace="0" style="vertical-align:top;" target="_blank" src="https://img.mailinblue.com/new_images/rnb/theme1/rnb_ico_gp.png"></span>';
		$sms .='																			</td></tr></tbody></table>';
		$sms .='																			</div><div class="rnb-social-center">';
		$sms .='																			<table align="left" style="float:left; display: inline-block" border="0" cellpadding="0" cellspacing="0">';
		$sms .='																			<tbody><tr>';
		$sms .='																					<td style="padding:0px 5px 5px 0px; mso-padding-alt: 0px 2px 5px 0px;" align="left">';
		$sms .='																			<span style="color:#ffffff; font-weight:normal;">';
		$sms .='																				<img alt="LinkedIn" border="0" hspace="0" vspace="0" style="vertical-align:top;" target="_blank" src="https://img.mailinblue.com/new_images/rnb/theme1/rnb_ico_in.png"></span>';
		$sms .='																			</td></tr></tbody></table>';
		$sms .='																			</div><div class="rnb-social-center">';
		$sms .='																			<table align="left" style="float:left; display: inline-block" border="0" cellpadding="0" cellspacing="0">';
		$sms .='																			<tbody><tr>';
		$sms .='																					<td style="padding:0px 5px 5px 0px; mso-padding-alt: 0px 2px 5px 0px;" align="left">';
		$sms .='																			<span style="color:#ffffff; font-weight:normal;">';
		$sms .='																				<img alt="Instagram" border="0" hspace="0" vspace="0" style="vertical-align:top;" target="_blank" src="https://img.mailinblue.com/new_images/rnb/theme1/rnb_ico_ig.png"></span>';
		$sms .='																			</td></tr></tbody></table>';
		$sms .='																			</div><div class="rnb-social-center">';
		$sms .='																			<table align="left" style="float:left; display: inline-block" border="0" cellpadding="0" cellspacing="0">';
		$sms .='																			<tbody><tr>';
		$sms .='																					<td style="padding:0px 5px 5px 0px; mso-padding-alt: 0px 2px 5px 0px;" align="left">';
		$sms .='																			<span style="color:#ffffff; font-weight:normal;">';
		$sms .='																				<img alt="YouTube" border="0" hspace="0" vspace="0" style="vertical-align:top;" target="_blank" src="https://img.mailinblue.com/new_images/rnb/theme1/rnb_ico_yt.png"></span>';
		$sms .='																			</td></tr></tbody></table>';
		$sms .='																			</div></td>';
		$sms .='																	</tr>';
		$sms .='																</tbody></table>';
		$sms .='															</td>';
		$sms .='														</tr>';
		$sms .='														</tbody></table>';
		$sms .='													</th></tr>';
		$sms .='										</tbody></table></td>';
		$sms .='								</tr>';
		$sms .='								<tr>';
		$sms .='									<td height="20" style="font-size:1px; line-height:20px; mso-hide: all;">&nbsp;</td>';
		$sms .='								</tr>';
		$sms .='							</tbody></table>';
		$sms .='						</td>';
		$sms .='					</tr></tbody></table>';
		$sms .='			</div></td>';
		$sms .='	</tr><tr>';
		$sms .='		<td align="center" valign="top">';
		$sms .='			<div style="background-color: rgb(249, 250, 252);">';
		$sms .='				<table class="rnb-del-min-width rnb-tmpl-width" width="100%" cellpadding="0" border="0" cellspacing="0" style="min-width:590px;" name="Layout_7" id="Layout_7">';
		$sms .='					<tbody><tr>';
		$sms .='						<td class="rnb-del-min-width" align="center" valign="top" style="min-width:590px;">';
		$sms .='							<a href="#" name="Layout_7"></a>';
		$sms .='							<table width="100%" cellpadding="0" border="0" align="center" cellspacing="0" bgcolor="#f9fafc" style="padding-right: 20px; padding-left: 20px; background-color: rgb(249, 250, 252);">';
		$sms .='								<tbody><tr>';
		$sms .='									<td height="20" style="font-size:1px; line-height:20px; mso-hide: all;">&nbsp;</td>';
		$sms .='								</tr>';
		$sms .='								<tr>';
		$sms .='									<td style="font-size:14px; color:#888888; font-weight:normal; text-align:center; font-family:Arial,Helvetica,sans-serif;">';
		$sms .='										<div><div>© 2020 ProgressIdea</div>';
		$sms .='</div>';
		$sms .='									</td></tr>';
		$sms .='								<tr>';
		$sms .='									<td height="20" style="font-size:1px; line-height:20px; mso-hide: all;">&nbsp;</td>';
		$sms .='								</tr>';
		$sms .='							</tbody></table>';
		$sms .='						</td>';
		$sms .='					</tr>';
		$sms .='				</tbody></table>';
		$sms .='			</div></td>';
		$sms .='	</tr></tbody></table>';
		$sms .='			<!--[if gte mso 9]>';
		$sms .='						</td>';
		$sms .='						</tr>';
		$sms .='						</table>';
		$sms .='						<![endif]-->';
		$sms .='						</td>';
		$sms .='		</tr>';
		$sms .='		</tbody></table>';
		$sms .='</body></html>';
		///////////////////////////////////////////////////////////////////////////////
	$fechaCreacion = date("Y-m-d");
	$fechaExpiracion = date("Y-m-d",strtotime($fechaCreacion."+ 1 days"));

		$inserta = mysqli_query($conexion, 'INSERT INTO  `recuperacioncuenta` (`idRecuperacion`, `estado`, `fechaExpiracion`, `fechaCreacion`, `idUsuario`) VALUE("'.$id.'", 1,"'.$fechaExpiracion.'","'.$fechaCreacion.'","'.$consulta['idRegistro'].'")')or die('<p>Error al registrar</p><br>'.mysqli_error($conexion));

		
	//$sms


	if ($name==""||$email==""||$sms=="") {
		echo '<div class="alert alert-warning" role="alert">todos los campos son requeridos!</div>';
	}else {
		$mail->From = $email;
		$mail->addAddress($to);
		$mail->Subject = $asunto;
		$mail->isHtml(true);
		
		$mail->Body = $sms;
		$mail->CharSet = 'UTF-8';
		$mail->send();
		echo "Se le ha enviado un correo, ve y revisalo!";
} 
}else{



}






?>

